### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by ghalevy** [F5Networks/f5-bigip-runtime-init#17]
Any idea what's happening here?

```
# f5-bigip-runtime-init --config-file /config/cloud/runtime-init-conf.yaml 
2021-04-10T00:17:40.329Z [13498]: info: Configuration file: /config/cloud/runtime-init-conf.yaml
2021-04-10T00:17:40.341Z [13498]: info: Validating provided declaration
2021-04-10T00:17:40.424Z [13498]: info: Successfully validated declaration
2021-04-10T00:17:40.425Z [13498]: info: Executing custom pre_onboard_enabled commands
2021-04-10T00:17:40.636Z [13498]: info: Shell command: /usr/bin/setdb provision.extramb 2048 execution completed; response: 
2021-04-10T00:17:40.837Z [13498]: info: Shell command: /usr/bin/setdb restjavad.useextramb true execution completed; response: 
2021-04-10T00:17:40.897Z [13498]: info: Resolving parameters
2021-04-10T00:17:40.917Z [13498]: info: Executing install operations.
2021-04-10T00:17:40.951Z [13498]: info: Initializing telemetryClient
2021-04-10T00:17:41.348Z [13498]: info: {"id":"eab980ce-a9c7-b347-1e2cff4a270b","product":"BIG-IP","cpuCount":16,"diskSize":217088,"memoryInMb":64431,"version":"15.1.2.1","nicCount":3,"regKey":"REDACTED","platformId":"Z100","hostname":"REDACTED","management":"REDACTED","provisionedModules":{"afm":"nominal","asm":"nominal","ltm":"nominal"},"installedPackages":{"f5-service-discovery-1.5.0-3.noarch":"1.5.0","f5-declarative-onboarding-1.19.0-2.noarch":"1.19.0","f5-appsvcs-3.26.0-5.noarch":"3.26.0","f5-telemetry-1.18.0-2.noarch":"1.18.0"},"environment":{"pythonVersion":"Python 2.7.5","pythonVersionDetailed":"2.7.5 (default, Jan 15 2021, 12:52:53) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]","nodeVersion":"v6.9.1","libraries":{"ssh":"OpenSSH_7.4p1, OpenSSL 1.0.2s-fips  28 May 2019"}}}
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /tmp/f5-bigip-runtime-init/src/lib/cloud/aws/cloudClient.js:284:30
    at errCallback (/tmp/f5-bigip-runtime-init/node_modules/aws-sdk/lib/util.js:891:7)
    at IncomingMessage.<anonymous> (/tmp/f5-bigip-runtime-init/node_modules/aws-sdk/lib/util.js:911:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

My config file 

```
# cat /config/cloud/runtime-init-conf.yaml 
---
runtime_parameters: []
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 2048
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
  install_operations:
    - extensionType: as3
      extensionVersion: 3.26.0
    - extensionType: do
      extensionVersion: 1.19.0
    - extensionType: ts
      extensionVersion: 1.18.0
```

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID ESECLDTPLT-2602.

**Comment by shyawnkarim** [comment]
Can you provide the logs from /var/log/cloud/startup-script.log?

**Comment by shyawnkarim** [comment]
Closing due to age. If this is still an issue for you, please submit another issue or comment here and I can open it back up.
