### ISSUE TITLE
error: RPM installation failed: undefined

### ISSUE THREAD

**Issue by ghalevy** [F5Networks/f5-bigip-runtime-init#18]
runtime-init log file

``` 
2021-04-10T00:55:06.912Z [19170]: info: Executing custom pre_onboard_enabled commands
2021-04-10T00:55:08.043Z [19170]: info: Shell command: /usr/bin/setdb provision.extramb 2048 execution completed; response: 
2021-04-10T00:55:08.165Z [19170]: info: Shell command: /usr/bin/setdb restjavad.useextramb true execution completed; response: 
2021-04-10T00:55:18.219Z [19170]: info: Resolving parameters
2021-04-10T00:55:18.230Z [19170]: info: Executing install operations.
2021-04-10T00:55:18.234Z [19170]: info: Installing - as3 3.26.0
2021-04-10T00:55:33.176Z [19170]: error: RPM installation failed: undefined
2021-04-10T00:55:33.177Z [19170]: info: Sending F5 Teem report for failure case.
2021-04-10T00:55:33.517Z [19170]: warn: Problem with getting data from /mgmt/tm/sys/license endpoint. Leaving regKey with default value
2021-04-10T00:55:33.518Z [19170]: info: {"id":"a8a09b25-bf5f-074d-551e1d412ed4","product":"BIG-IP","cpuCount":8,"diskSize":307200,"memoryInMb":64432,"version":"15.1.2","nicCount":3,"platformId":"Z100","hostname":"bigip1","management":"REDACTED","provisionedModules":{"ltm":"nominal"},"installedPackages":{},"environment":{"pythonVersion":"Python 2.7.5","pythonVersionDetailed":"2.7.5 (default, Nov 10 2020, 19:02:22) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]","nodeVersion":"v6.9.1","libraries":{"ssh":"OpenSSH_7.4p1, OpenSSL 1.0.2s-fips  28 May 2019"}}}
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /tmp/f5-bigip-runtime-init/src/lib/cloud/aws/cloudClient.js:284:30
    at ClientRequest.errCallback (/tmp/f5-bigip-runtime-init/node_modules/aws-sdk/lib/util.js:891:7)
    at ClientRequest.<anonymous> (/tmp/f5-bigip-runtime-init/node_modules/aws-sdk/lib/http/node.js:96:19)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
```

config file
```
---
runtime_parameters: []
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 2048
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
  install_operations:
    - extensionType: as3
      extensionVersion: 3.26.0
    - extensionType: do
      extensionVersion: 1.19.0
    - extensionType: ts
      extensionVersion: 1.18.0
```

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID ESECLDTPLT-2603.

**Comment by shyawnkarim** [comment]
Can you provide the logs from /var/log/cloud/startup-script.log?

**Comment by shyawnkarim** [comment]
Closing due to age. If this is still an issue for you, please submit another issue or comment here and I can open it back up.
